--reminder you must fill in anything that is XX PP QQ ZZ with no spaces!

USE [master];
--[]
CREATE DATABASE [CustomLog] CONTAINMENT = NONE ON PRIMARY (
	NAME = N'CustomLog'
	, FILENAME = N'XXPPQQZZ'
	, SIZE = 8192 KB
	, MAXSIZE = UNLIMITED
	, FILEGROWTH = 65536 KB
	) LOG ON (
	NAME = N'CustomLog_log'
	, FILENAME = N'XXPPQQZZ'
	, SIZE = 8192 KB
	, MAXSIZE = 2048 GB
	, FILEGROWTH = 65536 KB
	);

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
BEGIN
	EXEC [CustomLog].[dbo].[sp_fulltext_database] @action = 'enable'
END;

ALTER DATABASE [CustomLog] SET ANSI_NULL_DEFAULT OFF;

ALTER DATABASE [CustomLog] SET ANSI_NULLS OFF;

ALTER DATABASE [CustomLog] SET ANSI_PADDING OFF;

ALTER DATABASE [CustomLog] SET ANSI_WARNINGS OFF;

ALTER DATABASE [CustomLog] SET ARITHABORT OFF;

ALTER DATABASE [CustomLog] SET AUTO_CLOSE OFF;

ALTER DATABASE [CustomLog] SET AUTO_SHRINK OFF;

ALTER DATABASE [CustomLog] SET AUTO_UPDATE_STATISTICS ON;

ALTER DATABASE [CustomLog] SET CURSOR_CLOSE_ON_COMMIT OFF;

ALTER DATABASE [CustomLog] SET CURSOR_DEFAULT  GLOBAL;

ALTER DATABASE [CustomLog] SET CONCAT_NULL_YIELDS_NULL OFF;

ALTER DATABASE [CustomLog] SET NUMERIC_ROUNDABORT OFF;

ALTER DATABASE [CustomLog] SET QUOTED_IDENTIFIER OFF;

ALTER DATABASE [CustomLog] SET RECURSIVE_TRIGGERS OFF;

ALTER DATABASE [CustomLog] SET  ENABLE_BROKER;

ALTER DATABASE [CustomLog] SET AUTO_UPDATE_STATISTICS_ASYNC OFF;

ALTER DATABASE [CustomLog] SET DATE_CORRELATION_OPTIMIZATION OFF;

ALTER DATABASE [CustomLog] SET TRUSTWORTHY OFF;

ALTER DATABASE [CustomLog] SET ALLOW_SNAPSHOT_ISOLATION OFF;

ALTER DATABASE [CustomLog] SET PARAMETERIZATION SIMPLE;

ALTER DATABASE [CustomLog] SET READ_COMMITTED_SNAPSHOT OFF;

ALTER DATABASE [CustomLog] SET HONOR_BROKER_PRIORITY OFF;

ALTER DATABASE [CustomLog] SET RECOVERY FULL;

ALTER DATABASE [CustomLog] SET  MULTI_USER;

ALTER DATABASE [CustomLog] SET PAGE_VERIFY CHECKSUM ;

ALTER DATABASE [CustomLog] SET DB_CHAINING OFF;

ALTER DATABASE [CustomLog] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF );

ALTER DATABASE [CustomLog] SET TARGET_RECOVERY_TIME = 60 SECONDS;

ALTER DATABASE [CustomLog] SET DELAYED_DURABILITY = DISABLED;

ALTER DATABASE [CustomLog] SET QUERY_STORE = OFF;

ALTER DATABASE [CustomLog] SET  READ_WRITE;

ALTER DATABASE [CustomLog] 
   COLLATE Latin1_General_CS_AS; --case sensitivity is important damn it! -- Babler


USE [master];
CREATE LOGIN [Owner_CustomLog]
	WITH PASSWORD = N'XXPPQQZZ'
		, DEFAULT_DATABASE = [master]
		, CHECK_EXPIRATION = OFF
		, CHECK_POLICY = OFF;

USE [CustomLog];
CREATE USER [Owner_CustomLog]
FOR LOGIN [Owner_CustomLog];

USE [CustomLog];
ALTER USER [Owner_CustomLog]
	WITH DEFAULT_SCHEMA = [dbo];

USE [CustomLog];
ALTER ROLE [db_owner] ADD MEMBER [Owner_CustomLog];

USE [master];
GRANT CONNECT SQL
	TO [Owner_CustomLog];


USE [master]



CREATE SERVER ROLE [CustomLog_Connecter] AUTHORIZATION [serveradmin]



ALTER SERVER ROLE [CustomLog_Connecter] ADD MEMBER [Owner_CustomLog]



use [master]



GRANT ALTER ON LOGIN::[Owner_CustomLog] TO [CustomLog_Connecter]



use [master]



GRANT CONTROL ON LOGIN::[Owner_CustomLog] TO [CustomLog_Connecter]



use [master]



GRANT VIEW DEFINITION ON LOGIN::[Owner_CustomLog] TO [CustomLog_Connecter]



use [master]



GRANT CONNECT ON ENDPOINT::[TSQL Default TCP] TO [CustomLog_Connecter]



use [master]



GRANT VIEW DEFINITION ON ENDPOINT::[TSQL Default TCP] TO [CustomLog_Connecter]




